### ISSUE TITLE
Incomplete support for CPU 

### ISSUE THREAD

**Issue by wyfunique** [xhuang31/KEQA_WSDM19#1]
There is a bug when trying to use CPU using --no_cuda:

When using --no_cuda, args.gpu would be -1. But later when 'data.Iterator' is called, the args.gpu is passed into 'torch.device()' without checking. So there will be an error saying that parameter in 'torch.device()' cannot be negative as args.gpu == -1.

This bug exists in train_detection.py, train_entity.py, train_pred.py and test_main.py.

**Comment by xhuang31** [comment]
Thanks. It should be fine now. I changed the "device=args.gpu" to " device=torch.device('cuda', args.gpu)" before releasing. That is the code cause the bug.

Thanks.
