### ISSUE TITLE
ValueError: cannot reshape array of size 161914250 into shape (647639,250)

### ISSUE THREAD

**Issue by feitboiling** [xhuang31/KEQA_WSDM19#17]
Entity representation learning...
Traceback (most recent call last):
  File "train_entity.py", line 63, in <module>
    entities_emb = np.fromfile(os.path.join(args.output, 'entities_emb.bin'), dtype=np.float32).reshape((len(mid_dic), args.embed_dim))
**ValueError: cannot reshape array of size 161914250 into shape (647639,250)**
检查了 entity2id.txt,发现只有 647639，    
而entities_emb.bin读入后有161914250，#161914250/250=647657
请问如何解决？

**Comment by zhangzy6** [comment]
我也遇到了这个问题，请问如何解决的呢？

**Comment by feitboiling** [comment]
修改reshape的结果  len+18   就可以通过

**Comment by feitboiling** [comment]
修改reshape的结果 len+18 就可以通过
之后如果没有错误就会成功运行
当我第二次进行完整实验时，原来的 +18   就多余了
于是我改回到了原来的数字，就继续运行了

**Comment by zhangzy6** [comment]
非常谢谢，已经解决

**Comment by azhe1234** [comment]
> 修改reshape的结果 len+18 就可以通过 之后如果没有错误就会成功运行 当我第二次进行完整实验时，原来的 +18 就多余了 于是我改回到了原来的数字，就继续运行了
您还


> 修改reshape的结果 len+18 就可以通过 之后如果没有错误就会成功运行 当我第二次进行完整实验时，原来的 +18 就多余了 于是我改回到了原来的数字，就继续运行了

您好请问你成功复现了数据集FB2M的0.754的准确率了吗？为什么不加attention可以达到，但是加了反而准确率下降，但是论文里说加了attention，比较迷茫，请问您知道吗？
