### ISSUE TITLE
 I have some confusions，Can you help me?

### ISSUE THREAD

**Issue by BUGwf** [xhuang31/KEQA_WSDM19#8]
1.I find just part of entities and triples of FB2M are used in KEQA, and the baselines may use the whole FB2M, So the number of candidate answers of these methods are different, can we compare the result like this directly?
2.Why the final accuracy and all acc are different in the test result?I think if we know the head and relation,the tail should be unique in SimpleQuestions?
Looking forward to your reply，Thank you!

**Comment by xhuang31** [comment]
Thanks for your interest.

1. Using the entire FB2M would be too slow. A rough method is used to filter a small portion, i.e., if a fact's entities and predicate do not contain any words in the questions, then we remove them. Actually embedding more completed knowledge graphs would better support the KG embedding based method. So, it is fair.

2. In FreeBase, there are some facts share the same head entity and predicate, but with different tail entities. It is easy to search them.

Thanks.

**Comment by BUGwf** [comment]
I see. Thank you for your reply！
